all:
  children:
    raspberry_pis:
      hosts:
        rpi-1:
          ansible_host: 192.168.8.201
          ansible_user: ubuntu
        rpi-2:
          ansible_host: 192.168.8.202
          ansible_user: ubuntu
        rpi-3:
          ansible_host: 192.168.8.203
          ansible_user: ubuntu
        rpi-4:
          ansible_host: 192.168.8.204
          ansible_user: ubuntu
        rpi-5:
          ansible_host: 192.168.8.205
          ansible_user: ubuntu
        rpi-6:
          ansible_host: 192.168.8.206
          ansible_user: ubuntu
        rpi-7:
          ansible_host: 192.168.8.207
          ansible_user: ubuntu
        rpi-8:
          ansible_host: 192.168.8.208
          ansible_user: ubuntu          